AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CI / CD pipeline blueprint

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - release ## every second week from the master branch a release will be created and pushed to this branch wich is === production. Starts only if git tag was pushed!
      - master ## everyone pushes their code to the master, but before that the build gets verfied durin the pre-push phase
      - development ## this is a pre-push build, the infrastructure gets build before it gets pushed to master
  StackName:
    Type: String

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 5
    MemorySize: 128

Resources:
  GetNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      CodeUri: src/functions/get-name/
      Description: Is a dummy function that does some simpe property plucking with lenses
      FunctionName: 
        Fn::Sub:
          - getName-${_stack}-${_stage}
          - {_stack: {Ref: StackName }, _stage: {Ref: StageName}}

