AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CI / CD pipeline blueprint

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - Production ## is the protected branch 
      - Staging ## everyone pushes their code to the master
      - Development ## used for testing after the build process
      - Pre-Push ## before pushing the code to master developer verifies the version on his/her machine
    Default: Pre-Push
  ServiceName:
    Type: String
    Default: Pre-Push-Test

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 5
    MemorySize: 128

Resources:
  GetNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: src/functions/get-name/
      Description: Is a dummy function that does some simpe property plucking with lenses
      FunctionName: 
        Fn::Sub:
          - getName-${_service}-${_stage}
          - {_service: {Ref: ServiceName }, _stage: {Ref: StageName}}

